spring.application.name=aispring

server.port=8085
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/springai
spring.datasource.username=postgres
spring.datasource.password=

gemini.api.key=
spring.ai.google.ai.chat.options.model=gemini-1.5-flash

logging.level.org.springframework.web.client.RestClient=DEBUG
logging.level.org.apache.hc.client5.http=DEBUG