create table alunos (
    data_nascimento date,
    idade integer,
    id bigint generated by default as identity,
    cpf varchar(255),
    nome varchar(255),
    primary key (id),
    constraint uk_aluno_cpf unique (cpf)
);

create table cursos (
    ativo boolean,
    id bigint generated by default as identity,
    nome varchar(255),
    primary key (id),
    constraint uk_nome_curso unique (nome)
);

create table matriculas (
    data_inicio date,
    data_matricula date,
    data_termino date,
    aluno_id bigint,
    curso_id bigint,
    id bigint generated by default as identity,
    primary key (id),
    constraint uk_aluno_curso unique (aluno_id, curso_id)
);

alter table if exists matriculas 
   add constraint FKrwsrt4qf6q7fghkawume7g1ya 
   foreign key (aluno_id) 
   references alunos

alter table if exists matriculas 
   add constraint FKtgxnkauqy13npoi9q2t9n0ol5 
   foreign key (curso_id) 
   references cursos